spring:
  datasource:
    url: jdbc:h2:./testdb;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
server:
  port: 9090
  ssl:
    enabled: true
auditor:
  pool-size: 3
  receive-dir: audit
  agg-cycle: "* 0/30 * * * *"
